name: 'A debugger for actions'
description: 'A debugger for debugging actions online. It allows the user to login the action env and execute commands using ssh.'
author: 'shaowenchen'
inputs:
  frp_server_addr:
    required: true
    description: 'frp server addr'
    default: ''
  frp_server_port:
    required: true
    description: 'frp server port'
    default: ''
  frp_token:
    required: true
    description: 'frp token'
    default: ''
  ssh_port:
    required: true
    description: 'ss  port'
    default: '2222'
runs:
  using: 'node12'
  main: 'dist/index.js'
