name: 'build'
on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'  # 指定 Node.js 版本
      - name: install
        run: |
          npm install
      - name: run all
        run: |
          npm run all
