name: ngrok
on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  ngrok:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'  # 指定 Node.js 版本
      - name: build
        run: |
          npm install
          npm run all
      - uses: ./
        name: test actions
        timeout-minutes: 2
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          ngrok_addr_1: 30000
          ngrok_proto_1: tcp
          ngrok_addr_2: 30001
          ngrok_proto_2: tcp
          ngrok_addr_3: 30002
          ngrok_proto_3: tcp

      - uses: P3TERX/ssh2actions@main
        name: Start SSH via tmate
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
