name: example-ngrok-macos-shell-v2
on:
  workflow_dispatch:

jobs:
  example-ngrok-macos-shell-v2:
    runs-on: macos-latest
    steps:
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 300
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}