name: example-ngrok-buildx-v2
on:
  workflow_dispatch:

jobs:
  example-ngrok-buildx-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 300
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
